apiVersion: v2
name: cnpg
description: A Helm chart for installing cnpg cluster including NetworkPolicies

type: application

version: 0.5.0

dependencies:
- name: cluster
  version: 0.5.0
  repository: https://cloudnative-pg.github.io/charts
