netbox:
  postgresql:
    enabled: false
  externalDatabase:
    database: netbox
    engine: django.db.backends.postgresql
    existingSecretKey: password
    existingSecretName: netbox-app
    host: netbox-rw
    username: netbox

cluster:
  nameOverride: netbox
  fullnameOverride: netbox
  version:
    postgresql: "18"
  mode: standalone
  cluster:
    instances: 3
    storage:
      storageClass: ""
    walStorage:
      enabled: false
    initdb:
      database: netbox

deploy_network_policies: true
