{{- if .Values.deploy_network_policies -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-operator-to-postgresql-ingress
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/component: database
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: cloudnative-pg
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: cnpg-system
      ports:
      - port: 8000
        protocol: TCP
      - port: 9090
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgres-cluster
spec:
  policyTypes:
    - Egress
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/component: database
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: database
      ports:
      - port: 5432
        protocol: TCP
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: database
      ports:
      - port: 5432
        protocol: TCP
{{- end }}
