{{- if .Values.deploy_network_policies -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-postgresql-egress
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/component: netbox
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: database
      ports:
      - protocol: TCP
        port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-postgresql-ingress
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/component: database
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: netbox
      ports:
      - protocol: TCP
        port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-worker-to-postgresql-egress
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/component: worker
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: database
      ports:
      - protocol: TCP
        port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-worker-to-postgresql-ingress
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/component: database
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: worker
      ports:
      - protocol: TCP
        port: 5432
{{- end }}
