{{- if .Values.deploy_network_policies -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-operator-to-clusters-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
  egress:
    - ports:
      - protocol: TCP
        port: 5432
      - protocol: TCP
        port: 9090
      - protocol: TCP
        port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-operator-webhook-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
      - protocol: TCP
        port: 9443
{{- end }}
